#
# This source file is part of the Heartwood open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

dirs:
  - .
useGitIgnore: true
ignorePatterns:
  - pattern: '^doc:.*$'
  - pattern: '^http://localhost.*$'
  - pattern: '^https://schmiedmayerlab\.github\.io/heartwood/.*$'
replacementPatterns:
  - pattern: '(.*)#gh-dark-mode-only'
    replacement: '$1'
  - pattern: '(.*)#gh-light-mode-only'
    replacement: '$1'
