/*
 * This source file is part of the Heartwood open-source project
 *
 * SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * Generated from the gateway-owned Pydantic session projection.
 * Run `npm run contracts:generate` after changing a shared request or response.
 */
export const sessionProjectionJsonSchema = {
  $defs: {
    CommandKind: {
      enum: [
        "approve",
        "deny",
        "chat",
        "pause",
        "resume",
        "replay",
        "audit.export",
        "workflow",
      ],
      type: "string",
    },
    Digest: { pattern: "^[0-9a-f]{64}$", type: "string" },
    EvaluationIdentifier: {
      pattern: "^[A-Za-z0-9][A-Za-z0-9_.:/+-]{0,255}$",
      type: "string",
    },
    EventKind: {
      enum: [
        "command.received",
        "approval.recorded",
        "policy.decision.recorded",
        "model_call.decision.recorded",
        "user_message.recorded",
        "agent_message.emitted",
        "tool_call.proposed",
        "confirmation.requested",
        "confirmation.resolved",
        "tool.execution.recorded",
        "agent.lifecycle.updated",
        "task.plan.updated",
        "model.usage.updated",
        "subagent.updated",
        "session.paused",
        "session.resumed",
        "audit.export.recorded",
        "error.recorded",
        "workflow.updated",
        "workflow.execution.recorded",
      ],
      type: "string",
    },
    ExecutionBudget: {
      additionalProperties: false,
      properties: {
        maximum_actions: { exclusiveMinimum: 0, maximum: 100, type: "integer" },
        maximum_model_calls: {
          exclusiveMinimum: 0,
          maximum: 100,
          type: "integer",
        },
        maximum_reported_cost_usd: { exclusiveMinimum: 0, type: "number" },
        maximum_seconds: { exclusiveMinimum: 0, maximum: 3600, type: "number" },
        maximum_tokens: { exclusiveMinimum: 0, type: "integer" },
      },
      required: [
        "maximum_seconds",
        "maximum_model_calls",
        "maximum_tokens",
        "maximum_reported_cost_usd",
        "maximum_actions",
      ],
      type: "object",
    },
    ExecutionUsage: {
      additionalProperties: false,
      properties: {
        elapsed_seconds: { minimum: 0, type: "number" },
        input_tokens: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        model_calls: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        output_tokens: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        proposed_actions: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        reported_cost_usd: {
          anyOf: [{ minimum: 0, type: "number" }, { type: "null" }],
        },
      },
      required: ["elapsed_seconds"],
      type: "object",
    },
    ExperimentDefinition: {
      additionalProperties: false,
      properties: {
        actor_ref: { $ref: "#/$defs/Reference" },
        code: {
          items: { $ref: "#/$defs/ExperimentFile" },
          maxItems: 256,
          type: "array",
        },
        code_output_paths: {
          items: { $ref: "#/$defs/ExperimentPath" },
          maxItems: 256,
          type: "array",
        },
        entry_point: {
          anyOf: [{ $ref: "#/$defs/ExperimentPath" }, { type: "null" }],
        },
        environment: { $ref: "#/$defs/ExperimentEnvironment" },
        git_dirty: { anyOf: [{ type: "boolean" }, { type: "null" }] },
        git_revision: {
          anyOf: [
            { pattern: "^(?:[0-9a-f]{40}|[0-9a-f]{64})$", type: "string" },
            { type: "null" },
          ],
        },
        inputs: {
          items: { $ref: "#/$defs/ExperimentFile" },
          maxItems: 256,
          type: "array",
        },
        invocation_sha256: { $ref: "#/$defs/Digest" },
        output_paths: {
          items: { $ref: "#/$defs/ExperimentPath" },
          maxItems: 256,
          type: "array",
        },
        parameters_sha256: { $ref: "#/$defs/Digest" },
        source: { enum: ["python", "shell", "heartwood"], type: "string" },
        stage: {
          anyOf: [{ $ref: "#/$defs/ExperimentStage" }, { type: "null" }],
        },
      },
      required: [
        "actor_ref",
        "source",
        "entry_point",
        "code",
        "inputs",
        "output_paths",
        "code_output_paths",
        "environment",
        "parameters_sha256",
        "invocation_sha256",
        "git_revision",
        "git_dirty",
        "stage",
      ],
      type: "object",
    },
    ExperimentEnvironment: {
      additionalProperties: false,
      properties: {
        kind: { enum: ["python", "container", "declared"], type: "string" },
        sha256: { $ref: "#/$defs/Digest" },
        source: { enum: ["observed", "declared"], type: "string" },
      },
      required: ["kind", "sha256", "source"],
      type: "object",
    },
    ExperimentEvidence: {
      additionalProperties: false,
      properties: {
        event_id: { maxLength: 256, minLength: 1, type: "string" },
        event_sha256: { $ref: "#/$defs/Digest" },
        kind: { $ref: "#/$defs/Reference" },
      },
      required: ["event_id", "event_sha256", "kind"],
      type: "object",
    },
    ExperimentFile: {
      additionalProperties: false,
      properties: {
        path: { $ref: "#/$defs/ExperimentPath" },
        sha256: { $ref: "#/$defs/Digest" },
        size_bytes: { minimum: 0, type: "integer" },
      },
      required: ["path", "sha256", "size_bytes"],
      type: "object",
    },
    ExperimentPath: { maxLength: 512, minLength: 1, type: "string" },
    ExperimentRun: {
      additionalProperties: false,
      properties: {
        attempt: { minimum: 1, type: "integer" },
        definition: { $ref: "#/$defs/ExperimentDefinition" },
        evidence: {
          items: { $ref: "#/$defs/ExperimentEvidence" },
          type: "array",
        },
        exit_code: { anyOf: [{ type: "integer" }, { type: "null" }] },
        outputs: { items: { $ref: "#/$defs/ExperimentFile" }, type: "array" },
        run_id: { format: "uuid", type: "string" },
        schema_version: {
          const: "heartwood.experiment-run.v1",
          type: "string",
        },
        started_at: { format: "date-time", type: "string" },
        status: { $ref: "#/$defs/ExperimentStatus" },
        updated_at: { format: "date-time", type: "string" },
      },
      required: [
        "schema_version",
        "run_id",
        "definition",
        "started_at",
        "updated_at",
        "status",
        "attempt",
        "outputs",
        "exit_code",
        "evidence",
      ],
      type: "object",
    },
    ExperimentStage: {
      additionalProperties: false,
      properties: {
        correction_id: {
          anyOf: [{ $ref: "#/$defs/Reference" }, { type: "null" }],
        },
        session_id: { $ref: "#/$defs/Reference" },
        stage_id: { $ref: "#/$defs/Reference" },
        tool_call_id: {
          anyOf: [{ $ref: "#/$defs/Reference" }, { type: "null" }],
        },
        workflow_run_id: { $ref: "#/$defs/Reference" },
        workflow_sha256: { $ref: "#/$defs/Digest" },
      },
      required: [
        "session_id",
        "workflow_run_id",
        "stage_id",
        "workflow_sha256",
        "tool_call_id",
        "correction_id",
      ],
      type: "object",
    },
    ExperimentStatus: {
      enum: [
        "started",
        "interrupted",
        "resumed",
        "succeeded",
        "failed",
        "cancelled",
      ],
      type: "string",
    },
    JsonValue: {
      anyOf: [
        { type: "string" },
        { type: "number" },
        { type: "boolean" },
        { type: "null" },
        { items: { $ref: "#/$defs/JsonValue" }, type: "array" },
        { additionalProperties: { $ref: "#/$defs/JsonValue" }, type: "object" },
      ],
    },
    ParallelReviewPlan: {
      additionalProperties: false,
      properties: {
        case_id: { $ref: "#/$defs/EvaluationIdentifier" },
        evidence: {
          items: { $ref: "#/$defs/ReviewQualificationEvidence" },
          minItems: 6,
          type: "array",
        },
        parallel_configuration_fingerprint: { $ref: "#/$defs/Sha256" },
        policy: { $ref: "#/$defs/ParallelReviewPolicy" },
        purpose: { const: "qualified-review", type: "string" },
        scope: { $ref: "#/$defs/ReviewExecutionScope" },
        sequential_configuration_fingerprint: { $ref: "#/$defs/Sha256" },
        suite_fingerprint: { $ref: "#/$defs/Sha256" },
        valid_until: { format: "date-time", type: "string" },
      },
      required: [
        "scope",
        "suite_fingerprint",
        "case_id",
        "sequential_configuration_fingerprint",
        "parallel_configuration_fingerprint",
        "policy",
        "evidence",
        "valid_until",
      ],
      type: "object",
    },
    ParallelReviewPolicy: {
      additionalProperties: false,
      properties: {
        maximum_age_days: { exclusiveMinimum: 0, type: "integer" },
        maximum_cost_ratio: { minimum: 1, type: "number" },
        maximum_token_ratio: { minimum: 1, type: "number" },
        maximum_workers: { maximum: 16, minimum: 2, type: "integer" },
        minimum_latency_reduction: {
          exclusiveMaximum: 1,
          exclusiveMinimum: 0,
          type: "number",
        },
        minimum_repeats: { minimum: 3, type: "integer" },
      },
      type: "object",
    },
    ParallelReviewTrialPlan: {
      additionalProperties: false,
      properties: {
        case_id: { $ref: "#/$defs/EvaluationIdentifier" },
        configuration_fingerprint: { $ref: "#/$defs/Sha256" },
        purpose: { const: "qualification-trial", type: "string" },
        reservation_fingerprint: { $ref: "#/$defs/Sha256" },
        runtime_fingerprint: { $ref: "#/$defs/Sha256" },
        scope: { $ref: "#/$defs/ReviewExecutionScope" },
        seed: { minimum: 0, type: "integer" },
        suite_fingerprint: { $ref: "#/$defs/Sha256" },
        trial_id: { format: "uuid", type: "string" },
        valid_until: { format: "date-time", type: "string" },
      },
      required: [
        "scope",
        "suite_fingerprint",
        "case_id",
        "trial_id",
        "reservation_fingerprint",
        "seed",
        "configuration_fingerprint",
        "runtime_fingerprint",
        "valid_until",
      ],
      type: "object",
    },
    ProjectionActionDetails: {
      discriminator: {
        mapping: {
          "file-editor": "#/$defs/ProjectionFileEditorActionDetails",
          other: "#/$defs/ProjectionOtherActionDetails",
          task: "#/$defs/ProjectionTaskActionDetails",
          terminal: "#/$defs/ProjectionTerminalActionDetails",
        },
        propertyName: "kind",
      },
      oneOf: [
        { $ref: "#/$defs/ProjectionTerminalActionDetails" },
        { $ref: "#/$defs/ProjectionFileEditorActionDetails" },
        { $ref: "#/$defs/ProjectionTaskActionDetails" },
        { $ref: "#/$defs/ProjectionOtherActionDetails" },
      ],
    },
    ProjectionActionOutcome: {
      additionalProperties: false,
      properties: {
        exitCode: { type: "integer" },
        result: { anyOf: [{ type: "string" }, { type: "null" }] },
        resultTruncated: { type: "boolean" },
        summary: { type: "string" },
      },
      required: ["exitCode", "summary", "result", "resultTruncated"],
      type: "object",
    },
    ProjectionActionRecord: {
      additionalProperties: false,
      properties: {
        actionId: { anyOf: [{ type: "string" }, { type: "null" }] },
        affectedPaths: {
          items: { $ref: "#/$defs/ProjectionAffectedPath" },
          type: "array",
        },
        arguments: {
          additionalProperties: { $ref: "#/$defs/JsonValue" },
          type: "object",
        },
        decision: {
          anyOf: [
            { enum: ["approved", "rejected"], type: "string" },
            { type: "null" },
          ],
        },
        details: { $ref: "#/$defs/ProjectionActionDetails" },
        groupId: { anyOf: [{ type: "string" }, { type: "null" }] },
        outcome: {
          anyOf: [
            { $ref: "#/$defs/ProjectionActionOutcome" },
            { type: "null" },
          ],
        },
        proposedSequence: { minimum: 0, type: "integer" },
        risk: { enum: ["high", "low", "medium", "unknown"], type: "string" },
        schema_version: { const: "heartwood.action-record.v1", type: "string" },
        state: {
          enum: [
            "proposed",
            "awaiting-review",
            "approved",
            "rejected",
            "running",
            "succeeded",
            "failed",
            "outcome-unknown",
          ],
          type: "string",
        },
        summary: { type: "string" },
        toolCallId: { type: "string" },
        toolName: { type: "string" },
        updatedSequence: { minimum: 0, type: "integer" },
      },
      required: [
        "schema_version",
        "toolCallId",
        "actionId",
        "groupId",
        "toolName",
        "risk",
        "summary",
        "arguments",
        "details",
        "affectedPaths",
        "state",
        "decision",
        "outcome",
        "proposedSequence",
        "updatedSequence",
      ],
      type: "object",
    },
    ProjectionActivity: {
      additionalProperties: false,
      properties: {
        detail: { type: "string" },
        kind: { $ref: "#/$defs/EventKind" },
        label: { type: "string" },
        sequence: { minimum: 0, type: "integer" },
      },
      required: ["sequence", "kind", "label", "detail"],
      type: "object",
    },
    ProjectionAffectedPath: {
      additionalProperties: false,
      properties: {
        effect: {
          enum: ["created", "modified", "deleted", "unknown"],
          type: "string",
        },
        path: { type: "string" },
        provenance: { const: "file-editor-action", type: "string" },
      },
      required: ["path", "effect", "provenance"],
      type: "object",
    },
    ProjectionApprovalGroup: {
      additionalProperties: false,
      properties: {
        actions: {
          items: { $ref: "#/$defs/ProjectionActionRecord" },
          type: "array",
        },
        decision: {
          anyOf: [
            { enum: ["approved", "denied"], type: "string" },
            { type: "null" },
          ],
        },
        decisionScope: { const: "all", type: "string" },
        groupId: { type: "string" },
      },
      required: ["groupId", "actions", "decision", "decisionScope"],
      type: "object",
    },
    ProjectionCommandOutcome: {
      additionalProperties: false,
      properties: {
        commandId: { type: "string" },
        commandKind: { $ref: "#/$defs/CommandKind" },
        errorCode: { anyOf: [{ type: "string" }, { type: "null" }] },
        message: { anyOf: [{ type: "string" }, { type: "null" }] },
        status: { enum: ["accepted", "rejected"], type: "string" },
      },
      required: ["commandId", "commandKind", "status", "errorCode", "message"],
      type: "object",
    },
    ProjectionFileEditorActionDetails: {
      additionalProperties: false,
      properties: {
        kind: { const: "file-editor", type: "string" },
        operation: {
          enum: [
            "view",
            "create",
            "str_replace",
            "insert",
            "undo_edit",
            "unknown",
          ],
          type: "string",
        },
        path: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: ["kind", "operation", "path"],
      type: "object",
    },
    ProjectionLifecycleState: {
      additionalProperties: false,
      properties: {
        canPause: { type: "boolean" },
        canResume: { type: "boolean" },
        canSteer: { type: "boolean" },
        status: { $ref: "#/$defs/SessionLifecycle" },
      },
      required: ["status", "canPause", "canResume", "canSteer"],
      type: "object",
    },
    ProjectionMessage: {
      additionalProperties: false,
      properties: {
        content: { type: "string" },
        detail: { anyOf: [{ type: "string" }, { type: "null" }] },
        id: { type: "string" },
        label: { type: "string" },
        role: { enum: ["user", "agent", "trace"], type: "string" },
        sequence: { minimum: 0, type: "integer" },
        technicalDetail: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "id",
        "sequence",
        "role",
        "label",
        "content",
        "detail",
        "technicalDetail",
      ],
      type: "object",
    },
    ProjectionModelContext: {
      additionalProperties: false,
      properties: {
        modelDecision: { anyOf: [{ type: "string" }, { type: "null" }] },
        modelEndpoint: { anyOf: [{ type: "string" }, { type: "null" }] },
        modelReason: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: ["modelEndpoint", "modelDecision", "modelReason"],
      type: "object",
    },
    ProjectionOtherActionDetails: {
      additionalProperties: false,
      properties: { kind: { const: "other", type: "string" } },
      required: ["kind"],
      type: "object",
    },
    ProjectionResearcherNotice: {
      additionalProperties: false,
      properties: {
        code: { const: "request-not-applied", type: "string" },
        detail: { type: "string" },
        label: { type: "string" },
        noticeId: { type: "string" },
        tone: { enum: ["attention", "danger"], type: "string" },
      },
      required: ["noticeId", "code", "label", "detail", "tone"],
      type: "object",
    },
    ProjectionResearcherStatus: {
      additionalProperties: false,
      properties: {
        code: {
          enum: [
            "ready",
            "working",
            "waiting-for-review",
            "paused",
            "complete",
            "denied",
            "recoverable-failure",
            "terminal-failure",
          ],
          type: "string",
        },
        detail: { type: "string" },
        label: { type: "string" },
        recoverable: { type: "boolean" },
        tone: {
          enum: ["neutral", "progress", "attention", "success", "danger"],
          type: "string",
        },
      },
      required: ["code", "label", "detail", "tone", "recoverable"],
      type: "object",
    },
    ProjectionReviewExecution: {
      additionalProperties: false,
      properties: {
        budget: { $ref: "#/$defs/ExecutionBudget" },
        purpose: {
          enum: ["qualified-review", "qualification-trial"],
          type: "string",
        },
        reviewers: { items: { type: "string" }, type: "array" },
        status: {
          enum: [
            "preview",
            "authorized",
            "admitted",
            "assessed",
            "unavailable",
            "cancelled",
          ],
          type: "string",
        },
        summary: { type: "string" },
        workers: { minimum: 2, type: "integer" },
      },
      required: [
        "status",
        "purpose",
        "workers",
        "reviewers",
        "budget",
        "summary",
      ],
      type: "object",
    },
    ProjectionSubagent: {
      additionalProperties: false,
      properties: {
        agentName: { type: "string" },
        invocationId: { type: "string" },
        parentActionId: { type: "string" },
        parentSessionId: { type: "string" },
        resultSummary: { anyOf: [{ type: "string" }, { type: "null" }] },
        reviewProposals: {
          anyOf: [{ $ref: "#/$defs/ReviewProposals" }, { type: "null" }],
        },
        roleLabel: { type: "string" },
        status: {
          enum: ["proposed", "running", "completed", "error", "rejected"],
          type: "string",
        },
        statusLabel: { type: "string" },
        taskId: { anyOf: [{ type: "string" }, { type: "null" }] },
        taskSummary: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "invocationId",
        "taskId",
        "agentName",
        "roleLabel",
        "status",
        "statusLabel",
        "taskSummary",
        "resultSummary",
        "parentSessionId",
        "parentActionId",
        "reviewProposals",
      ],
      type: "object",
    },
    ProjectionSuggestion: {
      additionalProperties: false,
      properties: {
        kind: { enum: ["task", "follow-up", "recovery"], type: "string" },
        label: { type: "string" },
        prompt: { type: "string" },
        suggestionId: {
          enum: [
            "inspect-project",
            "plan-project",
            "continue-plan",
            "review-changes",
            "verify-work",
            "recover-task",
            "identify-next-step",
          ],
          type: "string",
        },
      },
      required: ["suggestionId", "label", "prompt", "kind"],
      type: "object",
    },
    ProjectionTask: {
      additionalProperties: false,
      properties: {
        status: { enum: ["todo", "in-progress", "done"], type: "string" },
        statusLabel: { type: "string" },
        title: { type: "string" },
      },
      required: ["title", "status", "statusLabel"],
      type: "object",
    },
    ProjectionTaskActionDetails: {
      additionalProperties: false,
      properties: {
        capability: {
          anyOf: [
            { enum: ["advisory", "project-actions"], type: "string" },
            { type: "null" },
          ],
        },
        description: { anyOf: [{ type: "string" }, { type: "null" }] },
        kind: { const: "task", type: "string" },
        prompt: { anyOf: [{ type: "string" }, { type: "null" }] },
        resume: { anyOf: [{ type: "string" }, { type: "null" }] },
        roleLabel: { anyOf: [{ type: "string" }, { type: "null" }] },
        subagentType: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "kind",
        "description",
        "prompt",
        "subagentType",
        "roleLabel",
        "capability",
        "resume",
      ],
      type: "object",
    },
    ProjectionTerminalActionDetails: {
      additionalProperties: false,
      properties: {
        command: { type: "string" },
        isInput: { type: "boolean" },
        kind: { const: "terminal", type: "string" },
        reset: { type: "boolean" },
        timeout: { anyOf: [{ minimum: 0, type: "number" }, { type: "null" }] },
      },
      required: ["kind", "command", "isInput", "timeout", "reset"],
      type: "object",
    },
    ProjectionUsage: {
      additionalProperties: false,
      properties: {
        accumulatedCost: { minimum: 0, type: "number" },
        cacheReadTokens: { minimum: 0, type: "integer" },
        cacheWriteTokens: { minimum: 0, type: "integer" },
        callCount: { minimum: 0, type: "integer" },
        completionTokens: { minimum: 0, type: "integer" },
        contextWindow: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        modelName: { type: "string" },
        promptTokens: { minimum: 0, type: "integer" },
        purposeLabel: { type: "string" },
        reasoningTokens: { minimum: 0, type: "integer" },
        usageId: { type: "string" },
      },
      required: [
        "usageId",
        "purposeLabel",
        "modelName",
        "callCount",
        "promptTokens",
        "completionTokens",
        "cacheReadTokens",
        "cacheWriteTokens",
        "reasoningTokens",
        "contextWindow",
        "accumulatedCost",
      ],
      type: "object",
    },
    Reference: {
      pattern: "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
      type: "string",
    },
    ResearchArtifactPath: {
      additionalProperties: false,
      properties: {
        artifact_id: { $ref: "#/$defs/WorkflowIdentifier" },
        path: { $ref: "#/$defs/ExperimentPath" },
      },
      required: ["artifact_id", "path"],
      type: "object",
    },
    ResearchCorrectionAttempt: {
      additionalProperties: false,
      properties: {
        assessment: {
          anyOf: [
            { $ref: "#/$defs/ReviewCorrectionAssessment" },
            { type: "null" },
          ],
        },
        attempt_id: { $ref: "#/$defs/Reference" },
        plan: { $ref: "#/$defs/ReviewCorrectionPlan" },
        started_sequence: { minimum: 0, type: "integer" },
        status: {
          enum: ["pending", "assessed", "unavailable", "cancelled"],
          type: "string",
        },
        unavailable_reason: {
          anyOf: [
            {
              enum: [
                "no-structured-outcome",
                "changed-context",
                "invalid-evidence",
                "admission-denied",
              ],
              type: "string",
            },
            { type: "null" },
          ],
        },
      },
      required: [
        "attempt_id",
        "plan",
        "started_sequence",
        "status",
        "assessment",
        "unavailable_reason",
      ],
      type: "object",
    },
    ResearchCorrectionRun: {
      additionalProperties: false,
      properties: {
        attempts: {
          items: { $ref: "#/$defs/ResearchCorrectionAttempt" },
          maxItems: 3,
          minItems: 1,
          type: "array",
        },
        correction_id: { $ref: "#/$defs/Reference" },
        maximum_attempts: { maximum: 3, minimum: 1, type: "integer" },
        review: { $ref: "#/$defs/ResearchReviewRun" },
        stage_id: { $ref: "#/$defs/WorkflowIdentifier" },
        stop_reason: {
          anyOf: [
            {
              enum: [
                "corrected",
                "attempt-limit",
                "budget",
                "unavailable",
                "cancelled",
              ],
              type: "string",
            },
            { type: "null" },
          ],
        },
      },
      required: [
        "correction_id",
        "stage_id",
        "review",
        "maximum_attempts",
        "attempts",
        "stop_reason",
      ],
      type: "object",
    },
    ResearchReviewRun: {
      additionalProperties: false,
      properties: {
        assessment: {
          anyOf: [{ $ref: "#/$defs/ReviewAssessment" }, { type: "null" }],
        },
        parallel_dispatch: {
          items: { $ref: "#/$defs/ReviewDispatchAction" },
          maxItems: 16,
          type: "array",
        },
        parallel_plan: {
          anyOf: [{ $ref: "#/$defs/ReviewExecutionPlan" }, { type: "null" }],
        },
        review_id: { $ref: "#/$defs/Reference" },
        reviewer_ids: {
          items: { $ref: "#/$defs/WorkflowIdentifier" },
          maxItems: 16,
          minItems: 1,
          type: "array",
        },
        snapshot: { $ref: "#/$defs/ReviewSnapshot" },
        started_sequence: { minimum: 0, type: "integer" },
        status: {
          enum: ["pending", "assessed", "unavailable", "cancelled"],
          type: "string",
        },
        submissions: {
          items: { $ref: "#/$defs/ReviewSubmission" },
          maxItems: 16,
          type: "array",
        },
        unavailable_reason: {
          anyOf: [
            {
              enum: [
                "incomplete-review",
                "invalid-review",
                "no-structured-outcome",
              ],
              type: "string",
            },
            { type: "null" },
          ],
        },
      },
      required: [
        "review_id",
        "snapshot",
        "reviewer_ids",
        "started_sequence",
        "status",
        "submissions",
        "assessment",
        "parallel_plan",
        "parallel_dispatch",
        "unavailable_reason",
      ],
      type: "object",
    },
    ResearchText: { maxLength: 4000, minLength: 1, type: "string" },
    ReviewArtifact: {
      additionalProperties: false,
      properties: {
        artifact_id: { $ref: "#/$defs/WorkflowIdentifier" },
        file: { $ref: "#/$defs/ExperimentFile" },
      },
      required: ["artifact_id", "file"],
      type: "object",
    },
    ReviewAssessment: {
      additionalProperties: false,
      properties: {
        findings: {
          items: { $ref: "#/$defs/ReviewFinding" },
          maxItems: 512,
          type: "array",
        },
        schema_version: {
          const: "heartwood.review-assessment.v1",
          type: "string",
        },
        snapshot_sha256: { $ref: "#/$defs/Digest" },
      },
      required: ["schema_version", "snapshot_sha256", "findings"],
      type: "object",
    },
    ReviewCandidate: {
      additionalProperties: false,
      properties: {
        artifact_ids: {
          items: { $ref: "#/$defs/WorkflowIdentifier" },
          maxItems: 16,
          minItems: 1,
          type: "array",
        },
        candidate_id: { $ref: "#/$defs/WorkflowIdentifier" },
        category: { $ref: "#/$defs/ReviewCategory" },
        condition: { $ref: "#/$defs/WorkflowIdentifier" },
        severity: { $ref: "#/$defs/ReviewSeverity" },
        summary: { $ref: "#/$defs/ResearchText" },
      },
      required: [
        "candidate_id",
        "condition",
        "category",
        "severity",
        "summary",
        "artifact_ids",
      ],
      type: "object",
    },
    ReviewCategory: {
      enum: ["coding", "statistical", "reproducibility"],
      type: "string",
    },
    ReviewCorrectionAssessment: {
      additionalProperties: false,
      properties: {
        checks: {
          items: { $ref: "#/$defs/ReviewCorrectionCheck" },
          maxItems: 512,
          minItems: 1,
          type: "array",
        },
        plan_sha256: { $ref: "#/$defs/Digest" },
        snapshot: {
          anyOf: [{ $ref: "#/$defs/ReviewSnapshot" }, { type: "null" }],
        },
      },
      required: ["plan_sha256", "snapshot", "checks"],
      type: "object",
    },
    ReviewCorrectionCheck: {
      additionalProperties: false,
      properties: {
        finding_id: { $ref: "#/$defs/Digest" },
        reason: { $ref: "#/$defs/WorkflowIdentifier" },
        status: {
          enum: ["not_observed", "still_observed", "unavailable", "stale"],
          type: "string",
        },
      },
      required: ["finding_id", "status", "reason"],
      type: "object",
    },
    ReviewCorrectionPlan: {
      additionalProperties: false,
      properties: {
        finding_ids: {
          items: { $ref: "#/$defs/Digest" },
          maxItems: 512,
          minItems: 1,
          type: "array",
        },
        output_directory: { maxLength: 512, minLength: 1, type: "string" },
        outputs: {
          items: { $ref: "#/$defs/ResearchArtifactPath" },
          maxItems: 32,
          minItems: 1,
          type: "array",
        },
        review_id: { $ref: "#/$defs/Reference" },
        snapshot_sha256: { $ref: "#/$defs/Digest" },
      },
      required: [
        "review_id",
        "snapshot_sha256",
        "finding_ids",
        "output_directory",
        "outputs",
      ],
      type: "object",
    },
    ReviewDispatchAction: {
      additionalProperties: false,
      properties: {
        action_fingerprint: { $ref: "#/$defs/Sha256" },
        event_id: { minLength: 1, type: "string" },
        reviewer_id: { $ref: "#/$defs/EvaluationIdentifier" },
        tool_call_id: { minLength: 1, type: "string" },
      },
      required: [
        "event_id",
        "tool_call_id",
        "reviewer_id",
        "action_fingerprint",
      ],
      type: "object",
    },
    ReviewExecutionPlan: {
      discriminator: {
        mapping: {
          "qualification-trial": "#/$defs/ParallelReviewTrialPlan",
          "qualified-review": "#/$defs/ParallelReviewPlan",
        },
        propertyName: "purpose",
      },
      oneOf: [
        { $ref: "#/$defs/ParallelReviewPlan" },
        { $ref: "#/$defs/ParallelReviewTrialPlan" },
      ],
    },
    ReviewExecutionScope: {
      additionalProperties: false,
      properties: {
        budget: { $ref: "#/$defs/ExecutionBudget" },
        project_fingerprint: { $ref: "#/$defs/Sha256" },
        reviewer_ids: {
          items: { $ref: "#/$defs/EvaluationIdentifier" },
          maxItems: 16,
          minItems: 2,
          type: "array",
        },
        revision: { minimum: 0, type: "integer" },
        session_id: { $ref: "#/$defs/EvaluationIdentifier" },
        snapshot_fingerprint: { $ref: "#/$defs/Sha256" },
        stage_id: { $ref: "#/$defs/EvaluationIdentifier" },
        workers: { maximum: 16, minimum: 2, type: "integer" },
        workflow_id: { $ref: "#/$defs/EvaluationIdentifier" },
        workflow_run_id: { $ref: "#/$defs/EvaluationIdentifier" },
      },
      required: [
        "project_fingerprint",
        "session_id",
        "workflow_run_id",
        "workflow_id",
        "stage_id",
        "revision",
        "snapshot_fingerprint",
        "reviewer_ids",
        "workers",
        "budget",
      ],
      type: "object",
    },
    ReviewFinding: {
      additionalProperties: false,
      properties: {
        category: { $ref: "#/$defs/ReviewCategory" },
        condition: { $ref: "#/$defs/WorkflowIdentifier" },
        disposition: { enum: ["open", "not_actionable"], type: "string" },
        evidence: { items: { $ref: "#/$defs/ReviewArtifact" }, type: "array" },
        finding_id: { $ref: "#/$defs/Digest" },
        reason: { $ref: "#/$defs/WorkflowIdentifier" },
        severity: { $ref: "#/$defs/ReviewSeverity" },
        sources: {
          items: { $ref: "#/$defs/ReviewSource" },
          maxItems: 512,
          minItems: 1,
          type: "array",
        },
        verification: { $ref: "#/$defs/ReviewVerification" },
        verified_claim: {
          anyOf: [{ $ref: "#/$defs/ResearchText" }, { type: "null" }],
        },
      },
      required: [
        "finding_id",
        "condition",
        "category",
        "severity",
        "verification",
        "disposition",
        "verified_claim",
        "reason",
        "evidence",
        "sources",
      ],
      type: "object",
    },
    ReviewProposals: {
      additionalProperties: false,
      properties: {
        candidates: {
          items: { $ref: "#/$defs/ReviewCandidate" },
          maxItems: 32,
          type: "array",
        },
      },
      required: ["candidates"],
      type: "object",
    },
    ReviewQualificationEvidence: {
      additionalProperties: false,
      properties: {
        record_fingerprint: { $ref: "#/$defs/Sha256" },
        run_id: { format: "uuid", type: "string" },
      },
      required: ["run_id", "record_fingerprint"],
      type: "object",
    },
    ReviewSeverity: {
      enum: ["low", "medium", "high", "critical"],
      type: "string",
    },
    ReviewSnapshot: {
      additionalProperties: false,
      properties: {
        artifacts: {
          items: { $ref: "#/$defs/ReviewArtifact" },
          maxItems: 32,
          minItems: 1,
          type: "array",
        },
        schema_version: {
          const: "heartwood.review-snapshot.v1",
          type: "string",
        },
      },
      required: ["schema_version", "artifacts"],
      type: "object",
    },
    ReviewSource: {
      additionalProperties: false,
      properties: {
        candidate: { $ref: "#/$defs/ReviewCandidate" },
        review_id: { $ref: "#/$defs/Reference" },
        reviewer_id: { $ref: "#/$defs/Reference" },
      },
      required: ["review_id", "reviewer_id", "candidate"],
      type: "object",
    },
    ReviewSubmission: {
      additionalProperties: false,
      properties: {
        candidates: {
          items: { $ref: "#/$defs/ReviewCandidate" },
          maxItems: 32,
          type: "array",
        },
        review_id: { $ref: "#/$defs/Reference" },
        reviewer_id: { $ref: "#/$defs/Reference" },
        schema_version: {
          const: "heartwood.review-submission.v1",
          type: "string",
        },
        snapshot_sha256: { $ref: "#/$defs/Digest" },
      },
      required: [
        "candidates",
        "schema_version",
        "review_id",
        "reviewer_id",
        "snapshot_sha256",
      ],
      type: "object",
    },
    ReviewVerification: {
      enum: ["verified", "rejected", "unsupported", "stale", "unavailable"],
      type: "string",
    },
    SessionLifecycle: {
      enum: [
        "idle",
        "running",
        "paused",
        "waiting-for-confirmation",
        "finished",
        "error",
      ],
      type: "string",
    },
    Sha256: { pattern: "^[a-f0-9]{64}$", type: "string" },
    WorkflowBoundInput: {
      additionalProperties: false,
      properties: {
        input_id: { $ref: "#/$defs/WorkflowIdentifier" },
        kind: { enum: ["file", "text"], type: "string" },
        sha256: { pattern: "^[0-9a-f]{64}$", type: "string" },
        value: { $ref: "#/$defs/WorkflowInputValue" },
      },
      required: ["input_id", "kind", "value", "sha256"],
      type: "object",
    },
    WorkflowCheckResult: {
      additionalProperties: false,
      properties: {
        check_id: { $ref: "#/$defs/WorkflowIdentifier" },
        evaluator_id: { $ref: "#/$defs/WorkflowIdentifier" },
        inspected: {
          items: { $ref: "#/$defs/WorkflowValueFingerprint" },
          type: "array",
        },
        status: { enum: ["passed", "failed", "not_run"], type: "string" },
      },
      required: ["check_id", "evaluator_id", "status", "inspected"],
      type: "object",
    },
    WorkflowControl: {
      additionalProperties: false,
      properties: {
        control_id: {
          enum: [
            "run",
            "evaluate",
            "accept",
            "decline",
            "cancel",
            "request-review",
            "correct",
            "prepare-parallel-review",
            "request-parallel-review",
          ],
          type: "string",
        },
        label: { $ref: "#/$defs/WorkflowText" },
        request: {
          anyOf: [
            { $ref: "#/$defs/WorkflowTransition" },
            { $ref: "#/$defs/WorkflowReviewRequest" },
            { $ref: "#/$defs/WorkflowReview" },
            { $ref: "#/$defs/WorkflowCorrectionRequest" },
          ],
        },
      },
      required: ["control_id", "label", "request"],
      type: "object",
    },
    WorkflowCorrectionRequest: {
      additionalProperties: false,
      properties: {
        action: { const: "correct", type: "string" },
        maximum_attempts: { maximum: 3, minimum: 1, type: "integer" },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
      },
      required: ["action", "run_id", "revision", "maximum_attempts"],
      type: "object",
    },
    WorkflowIdentifier: {
      pattern: "^[a-z][a-z0-9_.-]{0,127}$",
      type: "string",
    },
    WorkflowInputValue: { maxLength: 8000, minLength: 1, type: "string" },
    WorkflowProjectBinding: {
      additionalProperties: false,
      properties: {
        artifacts: {
          items: { $ref: "#/$defs/ResearchArtifactPath" },
          maxItems: 64,
          minItems: 1,
          type: "array",
        },
        inputs: {
          items: { $ref: "#/$defs/WorkflowBoundInput" },
          maxItems: 32,
          minItems: 1,
          type: "array",
        },
        output_directory: { maxLength: 512, minLength: 1, type: "string" },
        workflow_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
        workflow_id: { $ref: "#/$defs/WorkflowIdentifier" },
      },
      required: [
        "workflow_id",
        "workflow_fingerprint",
        "output_directory",
        "inputs",
        "artifacts",
      ],
      type: "object",
    },
    WorkflowReview: {
      additionalProperties: false,
      properties: {
        action: { const: "review", type: "string" },
        approved: { type: "boolean" },
        evidence_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
      },
      required: [
        "action",
        "run_id",
        "revision",
        "evidence_fingerprint",
        "approved",
      ],
      type: "object",
    },
    WorkflowReviewRequest: {
      additionalProperties: false,
      properties: {
        action: { const: "request-review", type: "string" },
        parallel_review_fingerprint: {
          anyOf: [
            { pattern: "^[0-9a-f]{64}$", type: "string" },
            { type: "null" },
          ],
        },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
      },
      required: ["action", "run_id", "revision", "parallel_review_fingerprint"],
      type: "object",
    },
    WorkflowRun: {
      additionalProperties: false,
      properties: {
        binding: { $ref: "#/$defs/WorkflowProjectBinding" },
        completed: {
          items: { $ref: "#/$defs/WorkflowStageEvaluation" },
          type: "array",
        },
        corrections: {
          items: { $ref: "#/$defs/ResearchCorrectionRun" },
          maxItems: 32,
          type: "array",
        },
        created_at: { format: "date-time", type: "string" },
        evaluation: {
          anyOf: [
            { $ref: "#/$defs/WorkflowStageEvaluation" },
            { type: "null" },
          ],
        },
        parallel_review_plan: {
          anyOf: [{ $ref: "#/$defs/ReviewExecutionPlan" }, { type: "null" }],
        },
        phase: {
          enum: [
            "ready",
            "running",
            "review",
            "blocked",
            "completed",
            "cancelled",
          ],
          type: "string",
        },
        research_review: {
          anyOf: [{ $ref: "#/$defs/ResearchReviewRun" }, { type: "null" }],
        },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
        stage_id: { $ref: "#/$defs/WorkflowIdentifier" },
        stage_started_at: {
          anyOf: [{ format: "date-time", type: "string" }, { type: "null" }],
        },
        stage_usage_baseline: {
          anyOf: [{ $ref: "#/$defs/ExecutionUsage" }, { type: "null" }],
        },
        started_sequence: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
      },
      required: [
        "run_id",
        "revision",
        "binding",
        "stage_id",
        "phase",
        "completed",
        "evaluation",
        "started_sequence",
        "created_at",
        "stage_started_at",
        "stage_usage_baseline",
        "research_review",
        "parallel_review_plan",
        "corrections",
      ],
      type: "object",
    },
    WorkflowStageAssessment: {
      additionalProperties: false,
      properties: {
        evidence_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
        evidence_satisfied: { type: "boolean" },
        reasons: { items: { type: "string" }, type: "array" },
        researcher_review_required: { type: "boolean" },
        stage_id: { $ref: "#/$defs/WorkflowIdentifier" },
        workflow_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
      },
      required: [
        "workflow_fingerprint",
        "stage_id",
        "evidence_fingerprint",
        "evidence_satisfied",
        "researcher_review_required",
        "reasons",
      ],
      type: "object",
    },
    WorkflowStageEvaluation: {
      additionalProperties: false,
      properties: {
        artifacts: {
          items: { $ref: "#/$defs/WorkflowValueFingerprint" },
          type: "array",
        },
        assessment: { $ref: "#/$defs/WorkflowStageAssessment" },
        checks: {
          items: { $ref: "#/$defs/WorkflowCheckResult" },
          type: "array",
        },
      },
      required: ["artifacts", "checks", "assessment"],
      type: "object",
    },
    WorkflowText: { maxLength: 8000, minLength: 1, type: "string" },
    WorkflowTransition: {
      additionalProperties: false,
      properties: {
        action: {
          enum: ["run", "evaluate", "cancel", "prepare-parallel-review"],
          type: "string",
        },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
      },
      required: ["action", "run_id", "revision"],
      type: "object",
    },
    WorkflowValueFingerprint: {
      additionalProperties: false,
      properties: {
        artifact_id: { $ref: "#/$defs/WorkflowIdentifier" },
        sha256: { pattern: "^[0-9a-f]{64}$", type: "string" },
      },
      required: ["artifact_id", "sha256"],
      type: "object",
    },
  },
  additionalProperties: false,
  properties: {
    actions: {
      items: { $ref: "#/$defs/ProjectionActionRecord" },
      type: "array",
    },
    activity: { items: { $ref: "#/$defs/ProjectionActivity" }, type: "array" },
    availableCommands: {
      items: {
        enum: ["chat", "pause", "resume", "approve", "deny"],
        type: "string",
      },
      type: "array",
    },
    context: { $ref: "#/$defs/ProjectionModelContext" },
    conversation: {
      items: { $ref: "#/$defs/ProjectionMessage" },
      type: "array",
    },
    eventCount: { minimum: 0, type: "integer" },
    experiments: { items: { $ref: "#/$defs/ExperimentRun" }, type: "array" },
    lastCommandOutcome: {
      anyOf: [{ $ref: "#/$defs/ProjectionCommandOutcome" }, { type: "null" }],
    },
    lifecycle: { $ref: "#/$defs/ProjectionLifecycleState" },
    paused: { readOnly: true, type: "boolean" },
    pendingApproval: {
      anyOf: [{ $ref: "#/$defs/ProjectionApprovalGroup" }, { type: "null" }],
    },
    researcherNotice: {
      anyOf: [{ $ref: "#/$defs/ProjectionResearcherNotice" }, { type: "null" }],
    },
    researcherStatus: { $ref: "#/$defs/ProjectionResearcherStatus" },
    reviewExecution: {
      anyOf: [{ $ref: "#/$defs/ProjectionReviewExecution" }, { type: "null" }],
    },
    revision: { minimum: -1, type: "integer" },
    schema_version: {
      const: "heartwood.session-projection.v1",
      type: "string",
    },
    sessionId: { type: "string" },
    streamEpoch: { type: "string" },
    streamRevision: { minimum: 0, type: "integer" },
    streamingText: { type: "string" },
    subagents: { items: { $ref: "#/$defs/ProjectionSubagent" }, type: "array" },
    suggestions: {
      items: { $ref: "#/$defs/ProjectionSuggestion" },
      type: "array",
    },
    taskPlan: { items: { $ref: "#/$defs/ProjectionTask" }, type: "array" },
    usage: { anyOf: [{ $ref: "#/$defs/ProjectionUsage" }, { type: "null" }] },
    usageByPurpose: {
      items: { $ref: "#/$defs/ProjectionUsage" },
      type: "array",
    },
    workflow: { anyOf: [{ $ref: "#/$defs/WorkflowRun" }, { type: "null" }] },
    workflowControls: {
      items: { $ref: "#/$defs/WorkflowControl" },
      type: "array",
    },
    workspaceRevision: { minimum: -1, type: "integer" },
  },
  required: [
    "schema_version",
    "sessionId",
    "workflow",
    "reviewExecution",
    "experiments",
    "workflowControls",
    "eventCount",
    "revision",
    "workspaceRevision",
    "streamEpoch",
    "streamRevision",
    "activity",
    "conversation",
    "actions",
    "pendingApproval",
    "context",
    "lifecycle",
    "researcherStatus",
    "researcherNotice",
    "lastCommandOutcome",
    "taskPlan",
    "usage",
    "usageByPurpose",
    "subagents",
    "suggestions",
    "streamingText",
    "availableCommands",
    "paused",
  ],
  type: "object",
} as const;
