/*
 * This source file is part of the Heartwood open-source project
 *
 * SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * Generated from the gateway-owned Pydantic session projection.
 * Run `npm run contracts:generate` after changing a shared request or response.
 */
export const sessionProjectionJsonSchema = {
  $defs: {
    CommandKind: {
      enum: [
        "approve",
        "deny",
        "chat",
        "pause",
        "resume",
        "replay",
        "audit.export",
        "workflow",
      ],
      type: "string",
    },
    EventKind: {
      enum: [
        "command.received",
        "approval.recorded",
        "policy.decision.recorded",
        "model_call.decision.recorded",
        "user_message.recorded",
        "agent_message.emitted",
        "tool_call.proposed",
        "confirmation.requested",
        "confirmation.resolved",
        "tool.execution.recorded",
        "agent.lifecycle.updated",
        "task.plan.updated",
        "model.usage.updated",
        "subagent.updated",
        "session.paused",
        "session.resumed",
        "audit.export.recorded",
        "error.recorded",
        "workflow.updated",
        "workflow.execution.recorded",
      ],
      type: "string",
    },
    ExecutionUsage: {
      additionalProperties: false,
      properties: {
        elapsed_seconds: { minimum: 0, type: "number" },
        input_tokens: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        model_calls: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        output_tokens: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        proposed_actions: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        reported_cost_usd: {
          anyOf: [{ minimum: 0, type: "number" }, { type: "null" }],
        },
      },
      required: ["elapsed_seconds"],
      type: "object",
    },
    JsonValue: {
      anyOf: [
        { type: "string" },
        { type: "number" },
        { type: "boolean" },
        { type: "null" },
        { items: { $ref: "#/$defs/JsonValue" }, type: "array" },
        { additionalProperties: { $ref: "#/$defs/JsonValue" }, type: "object" },
      ],
    },
    ProjectionActionDetails: {
      discriminator: {
        mapping: {
          "file-editor": "#/$defs/ProjectionFileEditorActionDetails",
          other: "#/$defs/ProjectionOtherActionDetails",
          task: "#/$defs/ProjectionTaskActionDetails",
          terminal: "#/$defs/ProjectionTerminalActionDetails",
        },
        propertyName: "kind",
      },
      oneOf: [
        { $ref: "#/$defs/ProjectionTerminalActionDetails" },
        { $ref: "#/$defs/ProjectionFileEditorActionDetails" },
        { $ref: "#/$defs/ProjectionTaskActionDetails" },
        { $ref: "#/$defs/ProjectionOtherActionDetails" },
      ],
    },
    ProjectionActionOutcome: {
      additionalProperties: false,
      properties: {
        exitCode: { type: "integer" },
        result: { anyOf: [{ type: "string" }, { type: "null" }] },
        resultTruncated: { type: "boolean" },
        summary: { type: "string" },
      },
      required: ["exitCode", "summary", "result", "resultTruncated"],
      type: "object",
    },
    ProjectionActionRecord: {
      additionalProperties: false,
      properties: {
        actionId: { anyOf: [{ type: "string" }, { type: "null" }] },
        affectedPaths: {
          items: { $ref: "#/$defs/ProjectionAffectedPath" },
          type: "array",
        },
        arguments: {
          additionalProperties: { $ref: "#/$defs/JsonValue" },
          type: "object",
        },
        decision: {
          anyOf: [
            { enum: ["approved", "rejected"], type: "string" },
            { type: "null" },
          ],
        },
        details: { $ref: "#/$defs/ProjectionActionDetails" },
        groupId: { anyOf: [{ type: "string" }, { type: "null" }] },
        outcome: {
          anyOf: [
            { $ref: "#/$defs/ProjectionActionOutcome" },
            { type: "null" },
          ],
        },
        proposedSequence: { minimum: 0, type: "integer" },
        risk: { enum: ["high", "low", "medium", "unknown"], type: "string" },
        schema_version: { const: "heartwood.action-record.v1", type: "string" },
        state: {
          enum: [
            "proposed",
            "awaiting-review",
            "approved",
            "rejected",
            "running",
            "succeeded",
            "failed",
            "outcome-unknown",
          ],
          type: "string",
        },
        summary: { type: "string" },
        toolCallId: { type: "string" },
        toolName: { type: "string" },
        updatedSequence: { minimum: 0, type: "integer" },
      },
      required: [
        "schema_version",
        "toolCallId",
        "actionId",
        "groupId",
        "toolName",
        "risk",
        "summary",
        "arguments",
        "details",
        "affectedPaths",
        "state",
        "decision",
        "outcome",
        "proposedSequence",
        "updatedSequence",
      ],
      type: "object",
    },
    ProjectionActivity: {
      additionalProperties: false,
      properties: {
        detail: { type: "string" },
        kind: { $ref: "#/$defs/EventKind" },
        label: { type: "string" },
        sequence: { minimum: 0, type: "integer" },
      },
      required: ["sequence", "kind", "label", "detail"],
      type: "object",
    },
    ProjectionAffectedPath: {
      additionalProperties: false,
      properties: {
        effect: {
          enum: ["created", "modified", "deleted", "unknown"],
          type: "string",
        },
        path: { type: "string" },
        provenance: { const: "file-editor-action", type: "string" },
      },
      required: ["path", "effect", "provenance"],
      type: "object",
    },
    ProjectionApprovalGroup: {
      additionalProperties: false,
      properties: {
        actions: {
          items: { $ref: "#/$defs/ProjectionActionRecord" },
          type: "array",
        },
        decision: {
          anyOf: [
            { enum: ["approved", "denied"], type: "string" },
            { type: "null" },
          ],
        },
        decisionScope: { const: "all", type: "string" },
        groupId: { type: "string" },
      },
      required: ["groupId", "actions", "decision", "decisionScope"],
      type: "object",
    },
    ProjectionCommandOutcome: {
      additionalProperties: false,
      properties: {
        commandId: { type: "string" },
        commandKind: { $ref: "#/$defs/CommandKind" },
        errorCode: { anyOf: [{ type: "string" }, { type: "null" }] },
        message: { anyOf: [{ type: "string" }, { type: "null" }] },
        status: { enum: ["accepted", "rejected"], type: "string" },
      },
      required: ["commandId", "commandKind", "status", "errorCode", "message"],
      type: "object",
    },
    ProjectionFileEditorActionDetails: {
      additionalProperties: false,
      properties: {
        kind: { const: "file-editor", type: "string" },
        operation: {
          enum: [
            "view",
            "create",
            "str_replace",
            "insert",
            "undo_edit",
            "unknown",
          ],
          type: "string",
        },
        path: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: ["kind", "operation", "path"],
      type: "object",
    },
    ProjectionLifecycleState: {
      additionalProperties: false,
      properties: {
        canPause: { type: "boolean" },
        canResume: { type: "boolean" },
        canSteer: { type: "boolean" },
        status: { $ref: "#/$defs/SessionLifecycle" },
      },
      required: ["status", "canPause", "canResume", "canSteer"],
      type: "object",
    },
    ProjectionMessage: {
      additionalProperties: false,
      properties: {
        content: { type: "string" },
        detail: { anyOf: [{ type: "string" }, { type: "null" }] },
        id: { type: "string" },
        label: { type: "string" },
        role: { enum: ["user", "agent", "trace"], type: "string" },
        sequence: { minimum: 0, type: "integer" },
        technicalDetail: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "id",
        "sequence",
        "role",
        "label",
        "content",
        "detail",
        "technicalDetail",
      ],
      type: "object",
    },
    ProjectionModelContext: {
      additionalProperties: false,
      properties: {
        modelDecision: { anyOf: [{ type: "string" }, { type: "null" }] },
        modelEndpoint: { anyOf: [{ type: "string" }, { type: "null" }] },
        modelReason: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: ["modelEndpoint", "modelDecision", "modelReason"],
      type: "object",
    },
    ProjectionOtherActionDetails: {
      additionalProperties: false,
      properties: { kind: { const: "other", type: "string" } },
      required: ["kind"],
      type: "object",
    },
    ProjectionResearcherNotice: {
      additionalProperties: false,
      properties: {
        code: { const: "request-not-applied", type: "string" },
        detail: { type: "string" },
        label: { type: "string" },
        noticeId: { type: "string" },
        tone: { enum: ["attention", "danger"], type: "string" },
      },
      required: ["noticeId", "code", "label", "detail", "tone"],
      type: "object",
    },
    ProjectionResearcherStatus: {
      additionalProperties: false,
      properties: {
        code: {
          enum: [
            "ready",
            "working",
            "waiting-for-review",
            "paused",
            "complete",
            "denied",
            "recoverable-failure",
            "terminal-failure",
          ],
          type: "string",
        },
        detail: { type: "string" },
        label: { type: "string" },
        recoverable: { type: "boolean" },
        tone: {
          enum: ["neutral", "progress", "attention", "success", "danger"],
          type: "string",
        },
      },
      required: ["code", "label", "detail", "tone", "recoverable"],
      type: "object",
    },
    ProjectionSubagent: {
      additionalProperties: false,
      properties: {
        agentName: { type: "string" },
        invocationId: { type: "string" },
        parentActionId: { type: "string" },
        parentSessionId: { type: "string" },
        resultSummary: { anyOf: [{ type: "string" }, { type: "null" }] },
        roleLabel: { type: "string" },
        status: {
          enum: ["proposed", "running", "completed", "error", "rejected"],
          type: "string",
        },
        statusLabel: { type: "string" },
        taskId: { anyOf: [{ type: "string" }, { type: "null" }] },
        taskSummary: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "invocationId",
        "taskId",
        "agentName",
        "roleLabel",
        "status",
        "statusLabel",
        "taskSummary",
        "resultSummary",
        "parentSessionId",
        "parentActionId",
      ],
      type: "object",
    },
    ProjectionSuggestion: {
      additionalProperties: false,
      properties: {
        kind: { enum: ["task", "follow-up", "recovery"], type: "string" },
        label: { type: "string" },
        prompt: { type: "string" },
        suggestionId: {
          enum: [
            "inspect-project",
            "plan-project",
            "continue-plan",
            "review-changes",
            "verify-work",
            "recover-task",
            "identify-next-step",
          ],
          type: "string",
        },
      },
      required: ["suggestionId", "label", "prompt", "kind"],
      type: "object",
    },
    ProjectionTask: {
      additionalProperties: false,
      properties: {
        status: { enum: ["todo", "in-progress", "done"], type: "string" },
        statusLabel: { type: "string" },
        title: { type: "string" },
      },
      required: ["title", "status", "statusLabel"],
      type: "object",
    },
    ProjectionTaskActionDetails: {
      additionalProperties: false,
      properties: {
        capability: {
          anyOf: [
            { enum: ["advisory", "project-actions"], type: "string" },
            { type: "null" },
          ],
        },
        description: { anyOf: [{ type: "string" }, { type: "null" }] },
        kind: { const: "task", type: "string" },
        prompt: { anyOf: [{ type: "string" }, { type: "null" }] },
        resume: { anyOf: [{ type: "string" }, { type: "null" }] },
        roleLabel: { anyOf: [{ type: "string" }, { type: "null" }] },
        subagentType: { anyOf: [{ type: "string" }, { type: "null" }] },
      },
      required: [
        "kind",
        "description",
        "prompt",
        "subagentType",
        "roleLabel",
        "capability",
        "resume",
      ],
      type: "object",
    },
    ProjectionTerminalActionDetails: {
      additionalProperties: false,
      properties: {
        command: { type: "string" },
        isInput: { type: "boolean" },
        kind: { const: "terminal", type: "string" },
        reset: { type: "boolean" },
        timeout: { anyOf: [{ minimum: 0, type: "number" }, { type: "null" }] },
      },
      required: ["kind", "command", "isInput", "timeout", "reset"],
      type: "object",
    },
    ProjectionUsage: {
      additionalProperties: false,
      properties: {
        accumulatedCost: { minimum: 0, type: "number" },
        cacheReadTokens: { minimum: 0, type: "integer" },
        cacheWriteTokens: { minimum: 0, type: "integer" },
        callCount: { minimum: 0, type: "integer" },
        completionTokens: { minimum: 0, type: "integer" },
        contextWindow: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
        modelName: { type: "string" },
        promptTokens: { minimum: 0, type: "integer" },
        purposeLabel: { type: "string" },
        reasoningTokens: { minimum: 0, type: "integer" },
        usageId: { type: "string" },
      },
      required: [
        "usageId",
        "purposeLabel",
        "modelName",
        "callCount",
        "promptTokens",
        "completionTokens",
        "cacheReadTokens",
        "cacheWriteTokens",
        "reasoningTokens",
        "contextWindow",
        "accumulatedCost",
      ],
      type: "object",
    },
    SessionLifecycle: {
      enum: [
        "idle",
        "running",
        "paused",
        "waiting-for-confirmation",
        "finished",
        "error",
      ],
      type: "string",
    },
    WorkflowBoundInput: {
      additionalProperties: false,
      properties: {
        input_id: { $ref: "#/$defs/WorkflowIdentifier" },
        kind: { enum: ["file", "text"], type: "string" },
        sha256: { pattern: "^[0-9a-f]{64}$", type: "string" },
        value: { maxLength: 8000, minLength: 1, type: "string" },
      },
      required: ["input_id", "kind", "value", "sha256"],
      type: "object",
    },
    WorkflowCheckResult: {
      additionalProperties: false,
      properties: {
        check_id: { $ref: "#/$defs/WorkflowIdentifier" },
        evaluator_id: { $ref: "#/$defs/WorkflowIdentifier" },
        inspected: {
          items: { $ref: "#/$defs/WorkflowValueFingerprint" },
          type: "array",
        },
        status: { enum: ["passed", "failed", "not_run"], type: "string" },
      },
      required: ["check_id", "evaluator_id", "status", "inspected"],
      type: "object",
    },
    WorkflowIdentifier: {
      pattern: "^[a-z][a-z0-9_.-]{0,127}$",
      type: "string",
    },
    WorkflowProjectBinding: {
      additionalProperties: false,
      properties: {
        inputs: {
          items: { $ref: "#/$defs/WorkflowBoundInput" },
          maxItems: 32,
          minItems: 1,
          type: "array",
        },
        output_directory: { maxLength: 512, minLength: 1, type: "string" },
        workflow_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
        workflow_id: { $ref: "#/$defs/WorkflowIdentifier" },
      },
      required: [
        "workflow_id",
        "workflow_fingerprint",
        "output_directory",
        "inputs",
      ],
      type: "object",
    },
    WorkflowRun: {
      additionalProperties: false,
      properties: {
        binding: { $ref: "#/$defs/WorkflowProjectBinding" },
        completed: {
          items: { $ref: "#/$defs/WorkflowStageEvaluation" },
          type: "array",
        },
        created_at: { format: "date-time", type: "string" },
        evaluation: {
          anyOf: [
            { $ref: "#/$defs/WorkflowStageEvaluation" },
            { type: "null" },
          ],
        },
        phase: {
          enum: [
            "ready",
            "running",
            "review",
            "blocked",
            "completed",
            "cancelled",
          ],
          type: "string",
        },
        revision: { minimum: 0, type: "integer" },
        run_id: { minLength: 1, type: "string" },
        stage_id: { $ref: "#/$defs/WorkflowIdentifier" },
        stage_started_at: {
          anyOf: [{ format: "date-time", type: "string" }, { type: "null" }],
        },
        stage_usage_baseline: {
          anyOf: [{ $ref: "#/$defs/ExecutionUsage" }, { type: "null" }],
        },
        started_sequence: {
          anyOf: [{ minimum: 0, type: "integer" }, { type: "null" }],
        },
      },
      required: [
        "run_id",
        "revision",
        "binding",
        "stage_id",
        "phase",
        "created_at",
      ],
      type: "object",
    },
    WorkflowStageAssessment: {
      additionalProperties: false,
      properties: {
        evidence_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
        evidence_satisfied: { type: "boolean" },
        reasons: { items: { type: "string" }, type: "array" },
        researcher_review_required: { type: "boolean" },
        stage_id: { $ref: "#/$defs/WorkflowIdentifier" },
        workflow_fingerprint: { pattern: "^[0-9a-f]{64}$", type: "string" },
      },
      required: [
        "workflow_fingerprint",
        "stage_id",
        "evidence_fingerprint",
        "evidence_satisfied",
        "researcher_review_required",
        "reasons",
      ],
      type: "object",
    },
    WorkflowStageEvaluation: {
      additionalProperties: false,
      properties: {
        artifacts: {
          items: { $ref: "#/$defs/WorkflowValueFingerprint" },
          type: "array",
        },
        assessment: { $ref: "#/$defs/WorkflowStageAssessment" },
        checks: {
          items: { $ref: "#/$defs/WorkflowCheckResult" },
          type: "array",
        },
      },
      required: ["artifacts", "checks", "assessment"],
      type: "object",
    },
    WorkflowValueFingerprint: {
      additionalProperties: false,
      properties: {
        artifact_id: { $ref: "#/$defs/WorkflowIdentifier" },
        sha256: { pattern: "^[0-9a-f]{64}$", type: "string" },
      },
      required: ["artifact_id", "sha256"],
      type: "object",
    },
  },
  additionalProperties: false,
  properties: {
    actions: {
      items: { $ref: "#/$defs/ProjectionActionRecord" },
      type: "array",
    },
    activity: { items: { $ref: "#/$defs/ProjectionActivity" }, type: "array" },
    availableCommands: {
      items: {
        enum: ["chat", "pause", "resume", "approve", "deny"],
        type: "string",
      },
      type: "array",
    },
    context: { $ref: "#/$defs/ProjectionModelContext" },
    conversation: {
      items: { $ref: "#/$defs/ProjectionMessage" },
      type: "array",
    },
    eventCount: { minimum: 0, type: "integer" },
    lastCommandOutcome: {
      anyOf: [{ $ref: "#/$defs/ProjectionCommandOutcome" }, { type: "null" }],
    },
    lifecycle: { $ref: "#/$defs/ProjectionLifecycleState" },
    paused: { readOnly: true, type: "boolean" },
    pendingApproval: {
      anyOf: [{ $ref: "#/$defs/ProjectionApprovalGroup" }, { type: "null" }],
    },
    researcherNotice: {
      anyOf: [{ $ref: "#/$defs/ProjectionResearcherNotice" }, { type: "null" }],
    },
    researcherStatus: { $ref: "#/$defs/ProjectionResearcherStatus" },
    revision: { minimum: -1, type: "integer" },
    schema_version: {
      const: "heartwood.session-projection.v1",
      type: "string",
    },
    sessionId: { type: "string" },
    streamEpoch: { type: "string" },
    streamRevision: { minimum: 0, type: "integer" },
    streamingText: { type: "string" },
    subagents: { items: { $ref: "#/$defs/ProjectionSubagent" }, type: "array" },
    suggestions: {
      items: { $ref: "#/$defs/ProjectionSuggestion" },
      type: "array",
    },
    taskPlan: { items: { $ref: "#/$defs/ProjectionTask" }, type: "array" },
    usage: { anyOf: [{ $ref: "#/$defs/ProjectionUsage" }, { type: "null" }] },
    usageByPurpose: {
      items: { $ref: "#/$defs/ProjectionUsage" },
      type: "array",
    },
    workflow: { anyOf: [{ $ref: "#/$defs/WorkflowRun" }, { type: "null" }] },
    workspaceRevision: { minimum: -1, type: "integer" },
  },
  required: [
    "schema_version",
    "sessionId",
    "workflow",
    "eventCount",
    "revision",
    "workspaceRevision",
    "streamEpoch",
    "streamRevision",
    "activity",
    "conversation",
    "actions",
    "pendingApproval",
    "context",
    "lifecycle",
    "researcherStatus",
    "researcherNotice",
    "lastCommandOutcome",
    "taskPlan",
    "usage",
    "usageByPurpose",
    "subagents",
    "suggestions",
    "streamingText",
    "availableCommands",
    "paused",
  ],
  type: "object",
} as const;
