# This source file is part of the Heartwood open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

name: Capable Model Pull Request Validation

on:
  pull_request:

concurrency:
  group: capable-model-pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  capable-model:
    name: Capable Model Acceptance
    uses: ./.github/workflows/capable-model.yml
